# This is a basic workflow to help you get started with Actions
name: run-train

# Run the workflow if new data is pushed to our /raw folder
on:
  push:
    branches:    
    - 'workflow-model'
    paths:
      - 'data/preprocessed/**.csv'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "preprocess"
  train:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Run python preprecoessing script
      - name: train-step
        run: |
          echo "Running model training pipeline"
          pip install pandas
          pip install numpy
          pip install scikit-learn
          python train.py
    # Step 3: Commit and push
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update preprocessed data: ${timestamp}" || exit 0
          git push

  
